# Generated by Django 3.1.4 on 2021-01-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicekey',
            name='apiKey',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicekey',
            name='serviceName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
