# Generated by Django 3.1.4 on 2021-01-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='profilePic',
            new_name='profilePicSize4',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='profilePicSize1',
            field=models.ImageField(default='defaultProfile.svg', upload_to='profilePic'),
        ),
        migrations.AddField(
            model_name='profilepic',
            name='profilePicSize2',
            field=models.ImageField(default='defaultProfile.svg', upload_to='profilePic'),
        ),
        migrations.AddField(
            model_name='profilepic',
            name='profilePicSize3',
            field=models.ImageField(default='defaultProfile.svg', upload_to='profilePic'),
        ),
    ]
