# Generated by Django 3.1.4 on 2021-01-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20210119_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize1',
            field=models.CharField(default='defaultProfile.svg', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize2',
            field=models.CharField(default='defaultProfile.svg', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize3',
            field=models.CharField(default='defaultProfile.svg', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize4',
            field=models.CharField(default='defaultProfile.svg', max_length=30),
        ),
    ]
