# Generated by Django 3.1.4 on 2021-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20210119_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize1',
            field=models.CharField(default='/authorizator/media/profilePic/defaultProfile.svg', max_length=150),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize2',
            field=models.CharField(default='/authorizator/media/profilePic/defaultProfile.svg', max_length=150),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize3',
            field=models.CharField(default='/authorizator/media/profilePic/defaultProfile.svg', max_length=150),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilePicSize4',
            field=models.CharField(default='/authorizator/media/profilePic/defaultProfile.svg', max_length=150),
        ),
    ]
