# Generated by Django 3.1.5 on 2021-01-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20210119_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicekey',
            name='canGet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicekey',
            name='canPost',
            field=models.BooleanField(default=False),
        ),
    ]
