# Generated by Django 3.1.5 on 2021-01-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiKeyManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grantedKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=30, unique=True)),
                ('apiKey', models.CharField(max_length=67, unique=True)),
            ],
        ),
    ]
