# Generated by Django 3.1.5 on 2021-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiKeyManagement', '0002_grantedkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantedkey',
            name='servicePath',
            field=models.CharField(default='/authoriazator/api/', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
